WebLogin/Models/CorreoDTO.cs
namespace WebLogin.Models
{
    public class CorreoDTO
    {
        public string Para { get; set; }
        public string Asunto { get; set; }
        public string Contenido { get; set; }
    }
}

WebLogin/Models/ErrorViewModel.cs
namespace WebLogin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebLogin/Models/UsuarioDTO.cs
namespace WebLogin.Models
{
    public class UsuarioDTO
    {
        public int IdUsuario { get; set; }

        public string Nombre { get; set; }

        public string Correo {  get; set; }

        public string Clave { get; set; }

        public string ConfirmarClave { get; set; }

        public bool Restablecer {  get; set; }

        public bool Confirmado { get; set; }

        public string Token {  get; set; }
    }
}

WebLogin/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebLogin.Models;

namespace WebLogin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebLogin/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;
using WebLogin.Models;
using WebLogin.Datos;
using WebLogin.Servicios;
using Microsoft.AspNetCore.Hosting;

namespace WebLogin.Controllers
{
    public class InicioController : Controller
    {
        private readonly PathService _pathService;

        public InicioController(PathService pathService)
        {
            _pathService = pathService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string correo, string clave)
        {
            UsuarioDTO usuario = DBUsuario.Validar(correo, UtilidadServicio.ConvertirSHA256(clave));

            if (usuario == null)
            {
                ViewBag.Mensaje = "No se encontró el usuario.";
                return View();
            }

            if (!usuario.Confirmado)
            {
                ViewBag.Mensaje = $"Falta confirmar su correo electrónico a {correo}.";
            }
            else if (usuario.Restablecer)
            {
                ViewBag.Mensaje = $"Se ha solicitado restablecer correo: {correo}.";
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(UsuarioDTO user)
        {
            if (user.Clave != user.ConfirmarClave)
            {
                ViewBag.Nombre = user.Nombre;
                ViewBag.Correo = user.Correo;
                ViewBag.Mensaje = "La contraseña no coinciden";
                return View();
            }

            if (DBUsuario.Obtener(user.Correo) == null)
            {
                user.Clave = UtilidadServicio.ConvertirSHA256(user.Clave);
                user.Token = UtilidadServicio.GenerarToken();
                user.Restablecer = false;
                user.Confirmado = false;
                bool res = DBUsuario.Registrar(user);

                if (res)
                {
                    // Usar PathService para obtener la ruta
                    string path = _pathService.ObtenerRutaArchivo("Confirmar.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}/Inicio/Confirmar?token={2}",
                            Request.Scheme,
                            Request.Host,
                            user.Token);

                    string htmlBody = string.Format(content, user.Nombre, url);

                    CorreoDTO correoDTO = new CorreoDTO()
                    {
                        Para = user.Correo,
                        Asunto = "Correo de Confirmacion",
                        Contenido = htmlBody,
                    };

                    bool send = CorreoServicio.Enviar(correoDTO);
                    ViewBag.Creado = true;
                    ViewBag.Mensaje = $"Su cuenta ha sido creada. Hemos enviado un mensaje al correo {user.Correo}";
                }
                else
                {
                    ViewBag.Creado = false;
                    ViewBag.Mensaje = "No se pudo crear su cuenta";
                }
            }
            else
            {
                ViewBag.Mensaje = "El correo ya se encuentra registrado";
            }

            return View();
        }

        public IActionResult Confirmar(string token)
        {
            ViewBag.Respuesta = DBUsuario.Confirmar(token);

            return View();
        }

        public IActionResult Restablecer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Restablecer(string correo)
        {
            UsuarioDTO user = DBUsuario.Obtener(correo);
            ViewBag.Correo = correo;

            if (user != null)
            {
                bool res = DBUsuario.ResTAct(1, user.Clave, user.Token);

                if (res)
                {
                    // Usar PathService para obtener la ruta
                    string path = _pathService.ObtenerRutaArchivo("Restablecer.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}/Inicio/Actualizar?token={2}",
                            Request.Scheme,
                            Request.Host,
                            user.Token);

                    string htmlBody = string.Format(content, user.Nombre, url);

                    CorreoDTO correoDTO = new CorreoDTO()
                    {
                        Para = user.Correo,
                        Asunto = "Restablecer cuenta",
                        Contenido = htmlBody,
                    };

                    bool send = CorreoServicio.Enviar(correoDTO);
                    ViewBag.Restablecido = true;
                    ViewBag.Mensaje = $"Verifique su correo. Se ha enviado la confirmacion {user.Correo}";

                }
                else
                {
                    ViewBag.Mensaje = "No se pudo restablecer la cuenta";
                }
            }
            else
            {
                ViewBag.Mensaje = "No se encontraron coincidencias con el correo";
            }

            return View();
        }

        public IActionResult Actualizar(string token)
        {
            ViewBag.Token = token;
            return View();
        }

        [HttpPost]
        public IActionResult Actualizar(string token, string clave, string confirmarClave)
        {
            ViewBag.Token = token;

            if (clave != confirmarClave)
            {
                ViewBag.Mensaje = "La contraseña no coinciden";
                return View();
            }

            bool res = DBUsuario.ResTAct(0, UtilidadServicio.ConvertirSHA256(clave), token);

            if (res)
            {
                ViewBag.Restablecido = true;
            }
            else
            {
                ViewBag.Mensaje = "No se pudo actualizar";
            }
            return View();
        }
    }
}

WebLogin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebLogin/Views/Inicio/Actualizar.cshtml
@{
    ViewData["Title"] = "Actualizar";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="row justify-content-center mt-5">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Actualizar</h3>
                </div>
                <div class="card-body">
                    @if (ViewBag.Restablecido == null)
                    {
                        <form action="@Url.Action("Actualizar","Inicio")" method="post">
                            <p>Ingrese su direccion de correo y le enviaremos un correo de recuperación de cuenta.</p>
                            <input type="hidden" name="token" value="ViewBag.Token" />
                            <div class="mb-3">
                                <label>Ingresar una nueva contraseña</label>
                                <input type="password" name="clave" class="form-control" required />
                            </div>
                            <div class="mb-3">
                                <label>Confirmar contraseña</label>
                                <input type="password" name="confirmarClave" class="form-control" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @(ViewBag.Mensaje)
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Cambiar contraseña</button>
                                </div>
                            </div>
                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>@(ViewBag.Mensaje)</p>
                            <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</body>
</html>

WebLogin/Views/Inicio/Confirmar.cshtml
@{
    ViewData["Title"] = "Confirmación";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="container mt-3">
        @if((bool)ViewBag.Respuesta){
            <div class="alert alert-success">
                <p><b>¡Listo!</b>&nbsp; Su cuenta ha sido confirmada.</p>
                <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Ingresar</a>
            </div>
        }else{
            <div class="alert alert-danger">
                <p><b>No se pudo confirmar su correo</b></p>
                <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Ingresar</a>
            </div>
        }
    </div>
</body>
</html>

WebLogin/Views/Inicio/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="row justify-content-center mt-5">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Login</h3>
                </div>
                <div class="card-body">
                    <form action="@Url.Action("Login","Inicio")" method="post">
                        <div class="mb-3">
                            <label>Correo</label>
                            <input type="email" name="correo" class="form-control" required />
                        </div>
                        <div class="mb-3">
                            <label>Contraseña</label>
                            <input type="password" name="clave" class="form-control" required />
                        </div>

                        @if (ViewBag.Mensaje != null)
                        {
                            <div class="alert alert-danger">
                                @(ViewBag.Mensaje)
                            </div>
                        }

                        <div class="mb-3">
                            <div class="d-grid">
                                <button class="btn btn-primary" type="submit">Ingresar</button>
                                <a class="btn btn-link" href="@Url.Action("Registrar","Inicio")">¿No tienes una cuenta? ¡Registrate!</a>
                                <a class="btn btn-link" href="@Url.Action("Restablecer","Inicio")">¿Has olvidado tú contraseña?</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

WebLogin/Views/Inicio/Registrar.cshtml
@{
    ViewData["Title"] = "Registrar";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="row justify-content-center mt-5">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Registrate</h3>

                    @if (ViewBag.Creado == null)
                    {
                        <form action="@Url.Action("Registrar","Inicio")" method="post">
                            <div class="mb-3">
                                <label>Nombre</label>
                                <input type="text" name="Nombre" value="@(ViewBag.Nombre ?? "")" class="form-control" required />
                            </div>
                            <div class="mb-3">
                                <label>Correo</label>
                                <input type="email" name="Correo" value="@(ViewBag.Correo ?? "")" class="form-control" required />
                            </div>
                            <div class="mb-3">
                                <label>Contraseña</label>
                                <input type="password" name="clave" class="form-control" required />
                            </div>
                            <div class="mb-3">
                                <label>Confirmar</label>
                                <input type="password" name="ConfirmarClave" class="form-control" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @(ViewBag.Mensaje)
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Registrarse</button>
                                    <a class="btn btn-link" href="@Url.Action("Registrar","Inicio")">¿No tienes una cuenta? ¡Registrate!</a>
                                    <a class="btn btn-link" href="@Url.Action("Login","Inicio")">¿Tienes una cuenta? Incia sesión</a>
                                </div>
                            </div>
                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>@(ViewBag.Mensaje)</p>
                            <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }
                </div>
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>
</body>
</html>

WebLogin/Views/Inicio/Restablecer.cshtml
@{
    ViewData["Title"] = "Restablecer";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="row justify-content-center mt-5">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Restablecer</h3>
                </div>
                <div class="card-body">
                    @if (ViewBag.Restablecido == null)
                    {
                        <form action="@Url.Action("Restablecer","Inicio")" method="post">
                            <p>Ingrese su direccion de correo y le enviaremos un correo de recuperación de cuenta.</p>

                            <div class="mb-3">
                                <label>Correo</label>
                                <input type="email" name="correo" value="@(ViewBag.Correo ?? "")" class="form-control" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @(ViewBag.Mensaje)
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Restablecer</button>
                                    <a class="btn btn-link" href="@Url.Action("Registrar","Inicio")">Volver</a>
                                    <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Volver</a>
                                </div>
                            </div>
                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>@(ViewBag.Mensaje)</p>
                            <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>

WebLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLogin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebLogin.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebLogin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>